version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker-modas-nansi/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development  
      - PORT=3000
      - LOCAL_DB_HOST=db
      - LOCAL_DB_PORT=3306
      - LOCAL_DB_USERNAME=root
      - LOCAL_DB_PASSWORD=password123
      - LOCAL_DB_DATABASE=modas-nansi-local
      - ENVIRONMENT=development
      - AWS_S3_BUCKET=dummy-bucket
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=dummy-key
      - AWS_SECRET_ACCESS_KEY=dummy-secret
      - JWT_SECRET=gT8+F6vs+hnEuCdvW2KkzxNmKy5YITc7evqhasTf8wfDAr2ji+EnU5ZnsAXlR2cMb0TO3Hjeccx33LYu8R7PNg==
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --bind-address=0.0.0.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: modas-nansi-local
      MYSQL_TCP_PORT: 3306
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword123"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

volumes:
  mysql_data: 